/*
 * Copyright (c) 2025 HUSTLER
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* HUSTLER coremark configuration
 */
#define CONFIG_COREMARK_ITERATIONS            120000 /* depends on platform */

#define CONFIG_COREMARK_THREADS_NUMBER        1
#define CONFIG_COREMARK_RUN_TYPE_PERFORMANCE  1
// #define CONFIG_COREMARK_RUN_TYPE_VALIDATION
// #define CONFIG_COREMARK_RUN_TYPE_PROFILE
#if CONFIG_COREMARK_RUN_TYPE_PERFORMANCE
#define CONFIG_COREMARK_DATA_SIZE             2000
#elif CONFIG_COREMARK_RUN_TYPE_VALIDATION
#define CONFIG_COREMARK_DATA_SIZE             500
#elif CONFIG_COREMARK_RUN_TYPE_PROFILE
#define CONFIG_COREMARK_DATA_SIZE             1200
#endif

// #define CONFIG_COREMARK_MEMORY_METHOD_STATIC  1
#define CONFIG_COREMARK_MEMORY_METHOD_STACK   1
